version: '3'
services:
    client:
        image: node:latest
        container_name: mr-gadget-client
        working_dir: /home/node/app
        volumes:
            - ./client:/home/node/app
        ports:
            - 3000:3000/tcp
        command: npm run start
        depends_on: 
            - server
        tty: false
        stdin_open: true
        environment: 
            - CHOKIDAR_USEPOLLING=true
    server:
        image: node:latest
        container_name: mr-gadget-server
        working_dir: /home/node/app
        environment: 
            - DATABASE_URL=mongodb://db-user:db-password@database:27017/dev-database
            - DEBUG=server:*
            - PORT=3100
        volumes:
            - ./server:/home/node/app
        ports:
            - 3100:3100/tcp
        command: npm run start
        depends_on: 
            - database
        tty: true
    database:
        image: mongo:latest
        container_name: mr-gadget-database
        environment: 
            - MONGO_INITDB_DATABASE=admin
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=password
        volumes:
            - database-volume:/data/db
            - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        ports:
            - 27019:27017/tcp
volumes:
    database-volume: